In [44]:
import pandas as pd

In [45]:
dataset = pd.read_csv("SPAM text message 20170820 - Data.csv")

In [46]:
dataset

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [47]:
dataset.shape

(5572, 2)

In [48]:
import re
import nltk

In [49]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91736\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [50]:
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [51]:
corpus = []
for i in range(0,len(dataset)):
    review = re.sub('[^a-zA-z0-9]'," ",dataset['Message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = " ".join(review)
    corpus.append(review)

In [52]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling 3 week word back like fun still tb ok xxx std chgs send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune',
 'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6days 16 tsandcs apply reply

In [53]:
## Creating bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary=True)
x = cv.fit_transform(corpus).toarray()

In [54]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
y = pd.get_dummies(dataset['Category'],dtype=int)

In [56]:
y = y.iloc[:,1].values

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [59]:
from sklearn.naive_bayes import MultinomialNB

In [60]:
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [61]:
ypred = spam_detect_model.predict(x_test)

In [62]:
from sklearn.metrics import classification_report,accuracy_score,f1_score

In [63]:
accuracy_score(y_test,ypred)

0.9836867862969005

In [64]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1593
           1       0.94      0.94      0.94       246

    accuracy                           0.98      1839
   macro avg       0.96      0.97      0.96      1839
weighted avg       0.98      0.98      0.98      1839



In [65]:
f1_score(y_test,ypred)

0.9392712550607287

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500)
x = tv.fit_transform(corpus).toarray()

In [67]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [69]:
from sklearn.naive_bayes import MultinomialNB
TFIDF_model = MultinomialNB().fit(x_train,y_train)

In [70]:
ypred = TFIDF_model.predict(x_test)

In [71]:
accuracy_score(y_test,ypred)

0.9832535885167464

In [72]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1448
           1       0.99      0.88      0.93       224

    accuracy                           0.98      1672
   macro avg       0.99      0.94      0.96      1672
weighted avg       0.98      0.98      0.98      1672



In [73]:
f1_score(y_test,ypred)

0.933649289099526

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [75]:
from sklearn.ensemble import  RandomForestClassifier
classifier = RandomForestClassifier()
rf_model = classifier.fit(x_train,y_train)

In [76]:
ypred = rf_model.predict(x_test)

In [77]:
accuracy_score(y_test,ypred)

0.9868421052631579

In [78]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1448
           1       1.00      0.90      0.95       224

    accuracy                           0.99      1672
   macro avg       0.99      0.95      0.97      1672
weighted avg       0.99      0.99      0.99      1672



In [79]:
f1_score(y_test,ypred)

0.9483568075117371

## Word2vec 

In [80]:
import gensim.downloader as api

In [81]:
w2v = api.load('word2vec-google-news-300')

## word2vec from scratch

In [82]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [83]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [84]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [85]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [86]:
import gensim

In [87]:
model = gensim.models.Word2Vec(words,window=5,min_count=2)

In [88]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'love',
 'text',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'home',
 'stop',
 'lor',
 'sorry',
 'see',
 'still',
 'take',
 'mobile',
 'back',
 'da',
 'dont',
 'reply',
 'think',
 'tell',
 'hi',
 'phone',
 'week',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'make',
 'dear',
 'night',
 'message',
 'say',
 'well',
 'min',
 'thing',
 'much',
 'great',
 'oh',
 'hope',
 'claim',
 'hey',
 'number',
 'give',
 'happy',
 'friend',
 'wat',
 'work',
 'way',
 'yes',
 'www',
 'let',
 'right',
 'tomorrow',
 'prize',
 'already',
 'win',
 'ask',
 'said',
 'amp',
 'cash',
 'life',
 'yeah',
 'im',
 'really',
 'tone',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'thanks',
 'uk',
 'last',
 'service',
 'anything',
 'would',
 'com',
 'care',
 'year',
 'nokia',
 'also',
 'lol',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'sent',
 'contact',
 'urgent',


In [89]:
model.corpus_count

5565

In [90]:
model.epochs

5

In [91]:
model.wv.similar_by_word('happy')

[('said', 0.9994867444038391),
 ('special', 0.9994598031044006),
 ('keep', 0.9994580745697021),
 ('amp', 0.9994485974311829),
 ('day', 0.9994418621063232),
 ('dear', 0.9994350671768188),
 ('find', 0.9994252324104309),
 ('god', 0.9994102716445923),
 ('one', 0.9994090795516968),
 ('go', 0.9994021654129028)]

In [92]:
import numpy as np

In [93]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [94]:
pip install tqdm

DEPRECATION: Loading egg at c:\users\91736\anaconda3\lib\site-packages\daimond_price_prediction-0.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [ ]:
x = []
for i in range(len(words)):
    x.append(avg_word2vec(words[i]))

c:\Users\91736\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\91736\anaconda3\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [122]:
x_new = np.array(x,dtype=object)

In [123]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [124]:
x_new.shape

(5565,)

In [125]:
y.shape

(5572,)

In [126]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=32)

ValueError: Found input variables with inconsistent numbers of samples: [5565, 5572]