In [1]:
import tensorflow as tf

## To check The Version

In [5]:
print(f"Tensorflow verson {tf.__version__}")
print(f"Tensorflow execution is {tf.executing_eagerly()}")
print(f"Keras Version {tf.keras.__version__}")

Tensorflow verson 2.19.0
Tensorflow execution is True
Keras Version 3.9.0


## CPU/GPU Check

In [7]:
if tf.test.is_gpu_available():
    print("Running on GPU")
else:
    print("Running on cpu")

Running on cpu


In [15]:
tf.config.list_logical_devices("CPU")

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [16]:
tf.config.list_logical_devices("GPU")

[]

## Constant

In [23]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [24]:
tf.constant(42,dtype="int64",shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[42, 42, 42],
       [42, 42, 42]], dtype=int64)>

In [25]:
arr = tf.constant(42)

In [27]:
arr.numpy()

42

In [29]:
arr1 = tf.constant([[4,2],[6,3]])

In [30]:
arr1.numpy()

array([[4, 2],
       [6, 3]])

## Methods to generate ones and zeros like np.ones or np.zeros its similar tf.ones and tf.zeros

In [31]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [32]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Adding two constant 

In [33]:
c1 = tf.constant([[1,2,3],[4,5,6]])
c2 = tf.constant([[1,2,3],[4,5,6]])
res = tf.add(c1,c2)
res

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

## Generating Random data

In [34]:
tf.random.normal(shape=(3,2),mean=5,stddev=2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[7.523615 , 5.159706 ],
       [7.5670385, 9.019377 ],
       [4.6931005, 6.985393 ]], dtype=float32)>

In [36]:
tf.random.uniform(shape=(3,3),minval=1,maxval=50,dtype=tf.int64)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[11,  4, 11],
       [43, 28, 31],
       [45, 28, 48]], dtype=int64)>

## Variables

In [38]:
var = tf.Variable(42)
var2 = tf.Variable([4,5,6])
var3 = tf.Variable([[1,2,3],[4,5,6]])
var4 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
var,var2,var3,var4

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>)

## Reassigning values using variable.assign()

In [39]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [40]:
var.assign(45)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=45>

In [41]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

## Shaping a tensor

In [42]:
var4

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [45]:
tf.reshape(var4,(1,9))

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])>

In [48]:
tf.reshape(var3,(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

## Ranking of a tensor

In [49]:
var3

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [50]:
tf.rank(var3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [57]:
var3[1][0]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [61]:
var3[1,0]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Casting a tensor to numpy or python variable

In [62]:
print(var4.numpy())

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Size of a tensor

In [64]:
tf.size(input=var4).numpy()

9

## Datatype of a tensor

In [66]:
var4.dtype

tf.int32