In [1]:
import tensorflow as tf

## To check The Version

In [2]:
print(f"Tensorflow verson {tf.__version__}")
print(f"Tensorflow execution is {tf.executing_eagerly()}")
print(f"Keras Version {tf.keras.__version__}")

Tensorflow verson 2.19.0
Tensorflow execution is True
Keras Version 3.9.0


## CPU/GPU Check

In [3]:
if tf.test.is_gpu_available():
    print("Running on GPU")
else:
    print("Running on cpu")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on cpu


In [4]:
tf.config.list_logical_devices("CPU")

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [5]:
tf.config.list_logical_devices("GPU")

[]

## Constant

In [6]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [7]:
tf.constant(42,dtype="int64",shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[42, 42, 42],
       [42, 42, 42]], dtype=int64)>

In [8]:
arr = tf.constant(42)

In [9]:
arr.numpy()

42

In [10]:
arr1 = tf.constant([[4,2],[6,3]])

In [11]:
arr1.numpy()

array([[4, 2],
       [6, 3]])

## Methods to generate ones and zeros like np.ones or np.zeros its similar tf.ones and tf.zeros

In [12]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Adding two constant 

In [14]:
c1 = tf.constant([[1,2,3],[4,5,6]])
c2 = tf.constant([[1,2,3],[4,5,6]])
res = tf.add(c1,c2)
res

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

## Generating Random data

In [15]:
tf.random.normal(shape=(3,2),mean=5,stddev=2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[6.9040546, 7.512447 ],
       [4.2940207, 5.1708317],
       [5.160619 , 7.3688974]], dtype=float32)>

In [16]:
tf.random.uniform(shape=(3,3),minval=1,maxval=50,dtype=tf.int64)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[20, 32, 23],
       [11, 10,  4],
       [29, 20,  3]], dtype=int64)>

## Variables

In [17]:
var = tf.Variable(42)
var2 = tf.Variable([4,5,6])
var3 = tf.Variable([[1,2,3],[4,5,6]])
var4 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
var,var2,var3,var4

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>)

## Reassigning values using variable.assign()

In [18]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [19]:
var.assign(45)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=45>

In [20]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

## Shaping a tensor

In [21]:
var4

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [22]:
tf.reshape(var4,(1,9))

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])>

In [23]:
tf.reshape(var3,(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

## Ranking of a tensor

In [24]:
var3

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [25]:
tf.rank(var3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
var3[1][0]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [27]:
var3[1,0]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Casting a tensor to numpy or python variable

In [28]:
print(var4.numpy())

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Size of a tensor

In [29]:
tf.size(input=var4).numpy()

9

## Datatype of a tensor

In [30]:
var4.dtype

tf.int32

## Mathematical Opreations

In [31]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
a,b,c,d,e

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.9597865 , -0.38280502],
        [ 1.8957822 , -0.31459484]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.6063419 , -0.41348803],
        [ 0.23717439, -2.217022  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.3534446, -0.796293 ],
        [ 2.1329565, -2.5316167]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.8318123 , 0.63408256],
        [4.5495033 , 6.409083  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.25834882, 0.4509977 ],
        [8.439782  , 0.07953034]], dtype=float32)>)

In [32]:
var2+var3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [ 8, 10, 12]])>

In [33]:
var3*var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 10, 18],
       [16, 25, 36]])>

In [34]:
var6 = var4/var2

In [35]:
var6

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.25, 0.4 , 0.5 ],
       [1.  , 1.  , 1.  ],
       [1.75, 1.6 , 1.5 ]])>

In [36]:
var4

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [37]:
var5 = var4*5

## MAtrix multiplication

In [38]:
tf.matmul(var4,tf.transpose(var5))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 70, 160, 250],
       [160, 385, 610],
       [250, 610, 970]])>

## Casting datatype

In [39]:
var6

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.25, 0.4 , 0.5 ],
       [1.  , 1.  , 1.  ],
       [1.75, 1.6 , 1.5 ]])>

In [40]:
tf.cast(var6,dtype=tf.int64)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)>

## Ragged tensor

In [41]:
r = tf.ragged.constant([[1],[1,2,3],[],[1,2,3,4]])

In [42]:
print(r)
print(r[0])
print(r[1])
print(r[2])
print(r[3])

<tf.RaggedTensor [[1], [1, 2, 3], [], [1, 2, 3, 4]]>
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


## Squared difference

In [43]:
tf.math.squared_difference(var,var2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1681, 1600, 1521])>

## Mean

In [44]:
tf.reduce_mean(input_tensor=var2)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [45]:
tf.reduce_mean(input_tensor=var2,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [46]:
tf.reduce_mean(input_tensor=var3,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

## Generating tensors filled with random values

In [47]:
tf.random.normal(shape=(6,6),mean=5,stddev=1)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[5.7372165, 4.5817976, 3.7488542, 5.2518344, 2.616666 , 5.827623 ],
       [4.61196  , 4.1603713, 3.9990754, 4.8354707, 3.7874665, 2.9368353],
       [4.654723 , 4.1975613, 3.3175063, 7.1277723, 5.1206183, 5.333952 ],
       [7.223585 , 3.6659412, 6.7640667, 5.492205 , 5.7231526, 4.556952 ],
       [4.6991863, 5.343246 , 5.1048055, 4.8684745, 3.7300727, 4.972345 ],
       [3.7522287, 5.0554757, 5.698037 , 5.8460693, 3.932814 , 5.583403 ]],
      dtype=float32)>

In [48]:
tf.random.uniform(shape=(6,6),minval=50,maxval=100,dtype=tf.int64)

<tf.Tensor: shape=(6, 6), dtype=int64, numpy=
array([[62, 86, 90, 52, 63, 97],
       [78, 95, 78, 88, 82, 70],
       [69, 72, 93, 60, 75, 60],
       [64, 67, 98, 99, 84, 98],
       [54, 61, 77, 82, 66, 82],
       [72, 78, 68, 70, 76, 63]], dtype=int64)>

## Set Seed

In [49]:
tf.random.set_seed(1)
val1 = tf.random.uniform(shape=(6,6),minval=50,maxval=100,dtype=tf.int64)
print(val1)

tf.Tensor(
[[66 63 84 62 84 78]
 [88 98 60 99 83 64]
 [83 80 72 80 73 84]
 [67 63 95 55 70 70]
 [78 65 79 96 89 85]
 [76 66 82 70 60 60]], shape=(6, 6), dtype=int64)


In [50]:
tf.random.set_seed(1) ## Same values
val2 = tf.random.uniform(shape=(6,6),minval=50,maxval=100,dtype=tf.int64)
print(val2)

tf.Tensor(
[[66 63 84 62 84 78]
 [88 98 60 99 83 64]
 [83 80 72 80 73 84]
 [67 63 95 55 70 70]
 [78 65 79 96 89 85]
 [76 66 82 70 60 60]], shape=(6, 6), dtype=int64)


## Concat

In [51]:
var5

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])>

In [52]:
var4

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [53]:
tf.concat(values=[var5,var4],axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])>

In [54]:
tf.concat(values=[var5,var4],axis=1)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 5, 10, 15,  1,  2,  3],
       [20, 25, 30,  4,  5,  6],
       [35, 40, 45,  7,  8,  9]])>

## Max min

In [55]:
var5

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])>

In [56]:
tf.argmax(input=var5)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 2], dtype=int64)>

In [57]:
tf.argmin(input=var5)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0], dtype=int64)>

In [58]:
tf.argsort(values=var5)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])>

In [59]:
var5

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])>

## Saving and restoring using a checkpoint

In [60]:
var5

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])>

In [61]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>
